### ISSUE TITLE
Please provide an example

### ISSUE THREAD

**Issue by gquemener** [devtyr/trello-burndown#1]
Hello,

Could you provide an example of the generated chart plz?

Just want to see what it looks like :smiley:

**Comment by devtyr** [comment]
Hi,

at the moment just a file (CSV) is exported. This can be an external data source, e.g. for Excel. That's how I use it at the moment. The file contains all necessary data:
- Day
- Estimate total
- Estimate ideal
- Estimate open
- Estimate done
- Effort
- Effort total

But this missing feature will be added soon.

**Comment by devtyr** [comment]
Charts via web server are available now. See [entry page](https://github.com/devtyr/trello-burndown) for a screenshot.
