### ISSUE TITLE
Specifying estimates on new cards?

### ISSUE THREAD

**Issue by juristr** [devtyr/trello-burndown#12]
Hi,

how am I supposed to specify estimates on new cards?? Consider I have the following Trello columns:
- Sprint backlog
- In progress
- Ready

where "Ready" is the finished stuff column.

When I move a card from my generic backlog into the Sprint backlog I'm going to estimate it, so I'm having a card like `[2|3] Some userstory`. This however **doesn't work** as the app breaks, because the real effort cannot be read (I guess there's a problem in the regex parsing those out.

How did you consider entering the real effort for new cards? With a 0, like `[2|3-0]`?

**Comment by juristr** [comment]
Moreover what do you think about adjusting the estimate specification pattern to [Trello-Scrum](https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje?hl=en)??

**Comment by devtyr** [comment]
Hi,

even for new cards to have to specify the title like `[priority|estimate-effort] My title` -> `[1|12-0] My Title`. After finishing the card, update the effort within the title.

I thought about doing it like Trello-Scrum but at the time I created this project there was no possibility to track effort what was necessary for my projects.

**Comment by juristr** [comment]
Ok I see. Well, related to Trello-Scrum I just thought about adjusting the regex for extracting the different kind of estimates/real work to work with Trello-Scrum. That means, instead of having a pattern like

```
[priority|estimate-effective]
```

we would have

```
[priority][effective](estimate)
```

This because Trello-Scrum uses the pattern `[effective](estimate)`.  
In this way one could use Trello-Scrum for specifying the estimates and having them nicely summed up on top of the different columns and also use Trello-Burndown for burndown charts. In case you want to take a look at it, I could submit a pull request as I have adjusted the regex for a project of mine.

**Comment by chris2cayi** [comment]
Using Trello-scrum for the estimate and effective pattern make a lot of sense, i am interested to look at it this as well.

**Comment by juristr** [comment]
Yep, also 'cause you get the estimate and effective hours nicely integrated in trello as well:
![trelloscrum](https://f.cloud.github.com/assets/542458/548375/0b775d8c-c2e2-11e2-9f0c-a2d4a58c77e3.png)

I adapted this project here and I'm currently experimenting how the combination of Trello-scrum and Trello-burndown works out on one of my projects.

**Comment by chris2cayi** [comment]
Ok great, and congrats to norbert for the great work on trello burndown

**Comment by devtyr** [comment]
@juristr / @chris2cayi You are right. I think it would be a good idea to support both patterns, to be compatible with sprints being in process. I'll give it a chance. Thanks for your great feedback.

**Comment by juristr** [comment]
If you want, then I can submit a pull request (tomorrow morning). I have it already working with Trello-Scrum.

**Comment by devtyr** [comment]
I just pushed the changes to the repository. Support for Scrum for Trello should be done now. Thank you very much, but maybe you can test my implementation. It worked for me in a simple test. 

Notation:
`[p|e](est) title`

It is possible to mix up both notation, even if this makes no sense.

**Comment by juristr** [comment]
Hmm..I can test it tomorrow as I'm currently just in front of my phone.
However the notation I used was [e](est) as in this way Trello Scrum also
nicely formats the effective hours on the cards (see my screenshot on a
prior comment)

I left the priority out as for me it is given by the order of the cards on
the backlog column. Once it is moved from there intoba sprint I don't care
about it any more.
But if wanted the priority could be appended like [p][e](est). What do you
think?

**Comment by devtyr** [comment]
You'll lost the order when moving the cards to other list. As everybody should only have one task in progress this wouldn't be important. You are right. But, in reality, it's different. As a scrum master you have no chance to track that.

Hmm .. why is it better to use `[p][e](est)` than `[p|e](est)` ?

**Comment by juristr** [comment]
I see.

It's not better to have the [p][e](est), it's just because Trello Scrum
uses exactly this kind of pattern to differentiate between the effective
effort and the estimate. Writing it as [p|e] would break that meaning that
Trello Scrum can't take the effort into account properly.

**Comment by chris2cayi** [comment]
hi agree with juri on the fact to keep as used by trello scrum as it's a very popular addon.
I also use the position in the list to determine the priority, moving the card from a list remain the same priority.
you could then extract the position parameter `pos` of the card to determine the priority.

so based on my need the order would be the following 
1. Estimate `(e)`
2. Effective `[e]`
3. Priority `|p|`

ps, i got trouble to have the webserver run node.js on windows or appfog, if you have any link for a wrap up documentation to send me by PM i would thrilled. the idea being to have trello-burndown accessible for my organisation :)

**Comment by devtyr** [comment]
Ah, allright. I missed the thing that Scrum for Trello supports effective efforts. I'll change that.

**Comment by devtyr** [comment]
@juristr I had a deeper look at Scrum for Trello. `[p][e](est)` does not work properly. `[p]` is evaluated as the effort, `[e]` is ignored by the pattern. I'll change it now to `[e](est)` and it is up to the user to put the priority into the title, or not.

**Comment by juristr** [comment]
@devtyr Ok, that makes sense.
