### ISSUE TITLE
Scrum for trello syntax not working

### ISSUE THREAD

**Issue by PortZar** [devtyr/trello-burndown#17]
Scrum for trello syntax not working
"(est) [esff]"

This is not working.  This syntax return this error:

"at CardStatistics.generate (/home/david/devel/node_modules/trello-burndown/lib/cardstatistics.js:37:14)
"

**Comment by devtyr** [comment]
Removing the whitespace between `)` and `[` should solve the issue.

**Comment by Copperfield** [comment]
I try this sintax:
"[1](1)"
"(1)[1]"
"[1](1)"
"(1) [1]"
And not working anything. I checked the regx and it return "null" in all cases.

**Comment by juristr** [comment]
Isn't the syntax `[effective](estimate)`

**Comment by devtyr** [comment]
@PortZar @juristr is right, it is `[effective](estimate)`. BUT, I've tested it today with the latest version of Scrum for Trello which can't handle effective points any more. Can someone confirm that?

**Comment by juristr** [comment]
@devtyr TrelloScrum still handles effective points, but oddly you now have to introduce a space in between the two indicators like `[6] (7)`…

**Comment by devtyr** [comment]
@juristr Ok, thanks. I'll do some updates and tests on trello-burndown.

**Comment by devtyr** [comment]
I've updated trello-burndown to be able to handle `[5] (3)` -> `[effective] (estimate)` (please note the whitespace between both parts).

**Comment by juristr** [comment]
Btw, did u succeed to correctly get the cards from the "done" list?? I am
having issues in getting it to work.

**Comment by juristr** [comment]
Oops sorry, saw your comment on the other issue just now.
