### ISSUE TITLE
Use all lists in a sprint

### ISSUE THREAD

**Issue by stupied4ever** [devtyr/trello-burndown#21]
What:
It would be nice if the parameter 'lists' were optional. And if no lists are given, it read lists from Trello.

Because:
We are using many lists in a sprint (each list is used for a story). To create a sprint is difficult because we need to configure all the lists, and some day during the sprint, rename a list, I will have q reconfigure or it will break.

If this is important to someone, I can implement. Just let me know.

**Comment by devtyr** [comment]
Do you have a list for finished tasks? How is your process for that?

**Comment by devtyr** [comment]
Any update?
