### ISSUE TITLE
Initial set up on a proxy environment

### ISSUE THREAD

**Issue by emanuelvianna** [devtyr/trello-burndown#23]
I'm interested to use trello-burndown, but I can't pass through the initial set up. 

I've made the following steps: 

1) Clone git repository from github
2) Set up the applicationKey, userToken and boardId in settings.json (checked them)
3) Start node app (which lunches properly)
4) Enter in node app and creates a Sprint pointing to my Trello board

But then, Node app can not retrieve data from Trello (probably due to a authentication issue) and repeats the the request several times as follows:

$ node run.js 
[STATUS] RestClient request send, URL: https://api.trello.com/1/boards/XXX/lists
[STATUS] RestClient request send, Method: GET
[STATUS] RestClient request send, URL: https://api.trello.com/1/boards/XXX/lists
[STATUS] RestClient request send, Method: GET

Is there something that I'm missing here?

Thanks in advance.

--Emanuel

**Comment by devtyr** [comment]
Try this via Fiddler, Chrome, FF:
https://api.trello.com/1/boards/BOARDID/lists?key=APPLICATIONKEY&token=USERTOKEN

Replace `BOARDID` with your configured board identifier and so on. If you receive a JSON containing a list of your Trello lists within that board, authentication is working. 

Does it work?

**Comment by emanuelvianna** [comment]
Thanks for the reply.

The request worked (opened the JSON properly) in Chrome and FF.

But the Node app can't retrieve the data yet.

--Emanuel

**Comment by devtyr** [comment]
Two more questions:

1) Which version of node are you running?
2) You created a sprint via the web interface. This should have created a JSON file under [node_module_folder]/trello-burndown/config/SPRINTNAME.json. Is it there and if so, how does it look like? Do all mentioned lists exist?

**Comment by emanuelvianna** [comment]
My node version is 0.10.20.

I've created a sprint via web interface and the JSON file has the following content (the boardId is right):

{
    "lists": "Sprint,Up for grabs,In Progress,Completed",
    "days": [
        ...
    ],
    "resources": [
        ...
    ],
    "finishedList": "Completed",
    "boardId": "XXX",
    "name": "Sprint IV"
}

And my settings.json is as follows (the applicationKey, userToken and boardId is right):

{
    "applicationKey":   "XXX",
    "userToken":        "YYY",
    "boardId":          "ZZZ",
    "port":             8008,
    "template":         "default.template",
    "home_template":    "home.template",
    "html_title":       "Trello burndown chart generator",
    "html_header":      "Burndown for sprint "
}

**Comment by devtyr** [comment]
Everything looks fine. 

Interessting that the `lists` action on the board is executed several times. Which OS are you running?

**Comment by emanuelvianna** [comment]
Ubuntu 13.04 with kernel Linux 3.8.0-19-generic and architecture x86_64.

**Comment by emanuelvianna** [comment]
I've figured out what is wrong.. my bad.

There is a proxy in the company where I work that is blocking the requests.

I'm looking for how to set up Node to deal with it.

**Comment by emanuelvianna** [comment]
I could bypass the proxy adding a proxy parameter to request (last line): 

node_modules/trello_ex/node_modules/rest-client/lib/index.js

env = {
    protocol: defaultURL.protocol,
    host: defaultURL.host,
    // url object
    url: url.format(defaultURL),
    // default use GET method
    method: 'GET',
    // default set 30 seconds
    timeout: 30000,
        // proxy settings
        proxy: 'XXX'
};

It exported cards successfully, but then I've got a 404 in other point.

[STATUS] RestClient request send, URL: https://api.trello.com/1/boards/XXX/lists
[STATUS] RestClient request send, Method: GET
[STATUS] RestClient request send, URL: https://api.trello.com/1/lists/XXX/cards
[STATUS] RestClient request send, Method: GET
FINISHED (1) Task 1
OPEN     (1) Task 2
OPEN     (1) Task 3

Statistics
Cards (total):    3
Cards (open):     2
Cards (finished): 1

Estimate (total): 3
Estimate (open):  2
Estimate (done):  1
Effort (total):   0
Diff estimate:    2

Exported successfully
404
404
404
404

The Sprint was created but the charts aren't being displayed (attached screenshot).

![selection_001](https://f.cloud.github.com/assets/3580848/1264938/724046a2-2c67-11e3-86e6-77c7f75e4312.png)

**Comment by devtyr** [comment]
Have you installed the dependency called `xcharts`?

**Comment by emanuelvianna** [comment]
Yes, I did, but it still doesn't plot the charts. I suppose that may be some other issue related to the proxy. 

I ended up creating an AWS instance (micro) to host trello-burndown and it is working very well. 

Now we can test it in our team. 

Thanks a lot for the help. 

Very best regards,
Emanuel
