### ISSUE TITLE
Change board ID format or provide example on retrieving one

### ISSUE THREAD

**Issue by IPWright83** [devtyr/trello-burndown#24]
The Trello board URL has changed to the following format:

   https://trello.com/b/D0WgCxAl/test-board

This means you can't simply copy and paste the GUID boardId. I managed to get one last time but can't remember how. It would be nice if it were made easier to obtain the board ID or some instructions on how to do so.

**Comment by devtyr** [comment]
The ID changed only for the client, internally Trello still uses GUIDs, but it is not easy to get it. It can be done by exporting the board into JSON. Not cool, but it works.

I will add the possibility to show a list of all boards by ID and name the given user has access to.

**Comment by devtyr** [comment]
Get the latest bits and call `node info.js` to get a list of all boards by name and id for the current user (settings must be provided, at least `applicationkey` and `usertoken`).

**Comment by IPWright83** [comment]
Thanks, that will be really useful. Good job. While I've got your attention
(I know this is unrelated) but can you have multiple burndowns across
boards? For example if each board is a project, I'd like burn downs for
each one. Happy to have multiple instances running via node.js but I'm not
sure if it's possible or how to achieve this. Could you provide any
suggestions?

Thanks

**Comment by devtyr** [comment]
trello-burndown does not support this out of the box, but you can run multiple instances. Copy trello-burndown as many times as you need it, change the port and boardid within the settings and start each with node. Hope that helps.

**Comment by IPWright83** [comment]
Yep - that's great. Thanks for all your help :)

**Comment by devtyr** [comment]
You're welcome :)
